version: "2.0"
volumes:
  pgdata:
services:
  db:
      # https://hub.docker.com/_/postgres/
      image: postgres:10-alpine
      restart: always
      volumes:
          - pgdata:/var/lib/postgresql/data/ttrss
      env_file: 
          - db.env

  web:
      image: olblak/ttrss
      restart: always
      env_file: 
          - web.env
      ports:
         - "8082:80"
      depends_on:
          - db
          - update

  update:
      image: olblak/ttrss
      restart: always
      env_file: 
          - web.env
      entrypoint: "su www-data -p -c 'php ./update_daemon2.php' -s /bin/bash"
