version: "2.0"
volumes:
  pgdata:
services:
  db:
      # https://hub.docker.com/_/postgres/
      image: postgres:10-alpine
      restart: always
      volumes:
          - pgdata:/var/lib/postgresql/data/ttrss
      env_file: 
          - db.env

  web:
      image: olblak/ttrss:b21ea8
      restart: always
      env_file: 
          - web.env
      ports:
         - "8082:80"
      depends_on:
          - db
          - update

  update:
      image: olblak/ttrss:b21ea8
      restart: always
      user: www-data
      working_dir: /var/www/html
      entrypoint: "php ./update_daemon2.php"
      env_file: 
          - web.env
